types:
  user: {}

  group:
    relations:
      member: ["user", "group"]

  folder:
    relations:
      parent: ["folder"]
      owner:  ["user", "group", "parent->owner"]
      editor: ["owner", "parent->editor"]
      viewer: ["editor", "parent->viewer"]

  doc:
    relations:
      parent: ["folder"]
      owner:  ["user", "group"]
      editor: ["owner", "parent->editor"]
      viewer: ["editor", "parent->viewer"]
